-- Generated by Oracle SQL Developer Data Modeler 21.2.0.183.1957
--   at:        2021-10-12 12:37:40 MSK
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE kmtm_teacher_subject (
    teacher_id        NUMBER NOT NULL,
    school_subject_id NUMBER NOT NULL
);

ALTER TABLE kmtm_teacher_subject ADD CONSTRAINT teacher_subject_pk PRIMARY KEY ( teacher_id,
                                                                                 school_subject_id );

CREATE TABLE knet_session (
    session_key  NUMBER NOT NULL,
    session_data CLOB NOT NULL,
    expire_time  DATE
);

ALTER TABLE knet_session ADD CONSTRAINT session_pk PRIMARY KEY ( session_key );

CREATE TABLE knet_users (
    id           NUMBER NOT NULL,
    is_superuser NUMBER NOT NULL,
    name         VARCHAR2(25) NOT NULL,
    surname      VARCHAR2(25) NOT NULL,
    patronymic   VARCHAR2(25),
    mail         VARCHAR2(45),
    username     VARCHAR2(20) NOT NULL,
    password     VARCHAR2(45) NOT NULL,
    is_active    NUMBER NOT NULL,
    last_login   DATE NOT NULL
);

ALTER TABLE knet_users ADD CONSTRAINT users_pk PRIMARY KEY ( id );

CREATE TABLE ksch_cabinet (
    id             NUMBER NOT NULL,
    cabinet_number NUMBER(5) NOT NULL,
    campus         VARCHAR2(20),
    school_id      NUMBER NOT NULL
);

ALTER TABLE ksch_cabinet ADD CONSTRAINT cabinet_pk PRIMARY KEY ( id );

CREATE TABLE ksch_class (
    id            NUMBER NOT NULL,
    start_year    DATE NOT NULL,
    end_year      DATE NOT NULL,
    name          VARCHAR2(1) NOT NULL,
    year_of_study NUMBER(2),
    teacher_id    NUMBER NOT NULL,
    school_id     NUMBER NOT NULL
);

ALTER TABLE ksch_class ADD CONSTRAINT class_pk PRIMARY KEY ( id );

CREATE TABLE ksch_journal_entry (
    id         NUMBER NOT NULL,
    mark       NUMBER(2),
    attendance NUMBER,
    student_id NUMBER NOT NULL,
    lesson_id  NUMBER NOT NULL
);

ALTER TABLE ksch_journal_entry ADD CONSTRAINT journal_entry_pk PRIMARY KEY ( id );

CREATE TABLE ksch_lesson (
    id                NUMBER NOT NULL,
    homework          CLOB,
    class_id          NUMBER NOT NULL,
    teacher_id        NUMBER NOT NULL,
    cabinet_id        NUMBER NOT NULL,
    school_subject_id NUMBER NOT NULL,
    lesson_time_id    NUMBER NOT NULL
);

ALTER TABLE ksch_lesson ADD CONSTRAINT lesson_pk PRIMARY KEY ( id );

CREATE TABLE ksch_lesson_time (
    id         NUMBER NOT NULL,
    start_time DATE,
    end_time   DATE
);

ALTER TABLE ksch_lesson_time ADD CONSTRAINT lesson_time_pk PRIMARY KEY ( id );

CREATE TABLE ksch_school (
    id          NUMBER NOT NULL,
    address     VARCHAR2(45) NOT NULL,
    school_name VARCHAR2(45) NOT NULL,
    mail        VARCHAR2(45),
    phone       VARCHAR2(12)
);

ALTER TABLE ksch_school ADD CONSTRAINT school_pk PRIMARY KEY ( id );

CREATE TABLE ksch_school_subject (
    id   NUMBER NOT NULL,
    name VARCHAR2(20)
);

ALTER TABLE ksch_school_subject ADD CONSTRAINT school_subject_pk PRIMARY KEY ( id );

CREATE TABLE ksch_student (
    id                     NUMBER NOT NULL,
    parent_mail            VARCHAR2(45),
    additional_information CLOB,
    users_id               NUMBER NOT NULL,
    class_id               NUMBER NOT NULL
);

ALTER TABLE ksch_student ADD CONSTRAINT student_pk PRIMARY KEY ( id );

CREATE TABLE ksch_teacher (
    id              NUMBER NOT NULL,
    education       VARCHAR2(45),
    work_experience VARCHAR2(45),
    fk              NUMBER,
    users_id        NUMBER NOT NULL,
    school_id       NUMBER NOT NULL
);

ALTER TABLE ksch_teacher ADD CONSTRAINT teacher_pk PRIMARY KEY ( id );

ALTER TABLE ksch_cabinet
    ADD CONSTRAINT cabinet_school_fk FOREIGN KEY ( school_id )
        REFERENCES ksch_school ( id );

ALTER TABLE ksch_class
    ADD CONSTRAINT class_school_fk FOREIGN KEY ( school_id )
        REFERENCES ksch_school ( id );

ALTER TABLE ksch_class
    ADD CONSTRAINT class_teacher_fk FOREIGN KEY ( teacher_id )
        REFERENCES ksch_teacher ( id );

ALTER TABLE ksch_journal_entry
    ADD CONSTRAINT journal_lesson_fk FOREIGN KEY ( lesson_id )
        REFERENCES ksch_lesson ( id );

ALTER TABLE ksch_journal_entry
    ADD CONSTRAINT journal_student_fk FOREIGN KEY ( student_id )
        REFERENCES ksch_student ( id );

ALTER TABLE ksch_lesson
    ADD CONSTRAINT lesson_cabinet_fk FOREIGN KEY ( cabinet_id )
        REFERENCES ksch_cabinet ( id );

ALTER TABLE ksch_lesson
    ADD CONSTRAINT lesson_class_fk FOREIGN KEY ( class_id )
        REFERENCES ksch_class ( id );

ALTER TABLE ksch_lesson
    ADD CONSTRAINT lesson_subject_fk FOREIGN KEY ( school_subject_id )
        REFERENCES ksch_school_subject ( id );

ALTER TABLE ksch_lesson
    ADD CONSTRAINT lesson_teacher_fk FOREIGN KEY ( teacher_id )
        REFERENCES ksch_teacher ( id );

ALTER TABLE ksch_lesson
    ADD CONSTRAINT lesson_time_fk FOREIGN KEY ( lesson_time_id )
        REFERENCES ksch_lesson_time ( id );

ALTER TABLE ksch_student
    ADD CONSTRAINT student_class_fk FOREIGN KEY ( class_id )
        REFERENCES ksch_class ( id );

ALTER TABLE ksch_student
    ADD CONSTRAINT student_users_fk FOREIGN KEY ( users_id )
        REFERENCES knet_users ( id );

ALTER TABLE ksch_teacher
    ADD CONSTRAINT teacher_school_fk FOREIGN KEY ( school_id )
        REFERENCES ksch_school ( id );

ALTER TABLE kmtm_teacher_subject
    ADD CONSTRAINT teacher_subject_subject_fk FOREIGN KEY ( school_subject_id )
        REFERENCES ksch_school_subject ( id );

ALTER TABLE kmtm_teacher_subject
    ADD CONSTRAINT teacher_subject_teacher_fk FOREIGN KEY ( teacher_id )
        REFERENCES ksch_teacher ( id );

ALTER TABLE ksch_teacher
    ADD CONSTRAINT teacher_users_fk FOREIGN KEY ( users_id )
        REFERENCES knet_users ( id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             0
-- ALTER TABLE                             28
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
