CONNECT &username/&password@&db
;
CREATE SEQUENCE seq_tariff_plan MINVALUE 1 START WITH 1 INCREMENT BY 1
;
CREATE SEQUENCE seq_subscriber MINVALUE 1 START WITH 1 INCREMENT BY 1
;
CREATE SEQUENCE seq_services MINVALUE 1 START WITH 1 INCREMENT BY 1
;
CREATE SEQUENCE seq_connected_services MINVALUE 1 START WITH 1 INCREMENT BY 1
;